### ISSUE TITLE
Add 👍 and 👎

### ISSUE THREAD

**Issue by RalphORama** [RadBuilder/EmojiChat#23]
### What do you think should be added/changed?  

I think the addition of 👍 and 👎 would be useful (I'm biased, it's one of my most frequently used Emojis)

### Any additional information that you would like to provide that would be helpful/relevant?  

N/a

**Comment by squidee100** [comment]
They're added as :+1: and :-1:

**Comment by zaneshaw** [comment]
They're added as "+1" and "-1"
